hide_download: true
hide_download_original: null
leftnav:
- identifier: fde08789-0797-2a22-26a7-3c3a2b53cb45
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: bf777819-1035-4bdf-e6e5-667477e0fa27
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 13d68a73-247e-5223-26c6-a5506c2e8176
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 8803411b-bebc-a133-80a7-a21a0cb51fce
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
